// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbW3WGWdEJL8iIzWHVHlwUzdYmOuTpLA',
    appId: '1:1085502128077:web:f9bff6ef47d18359d60e84',
    messagingSenderId: '1085502128077',
    projectId: 'quiz-app-7e9b3',
    authDomain: 'quiz-app-7e9b3.firebaseapp.com',
    storageBucket: 'quiz-app-7e9b3.appspot.com',
    measurementId: 'G-Y4MZMZQFWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYixb0a823zuw9PWBjAalvQElZRLVquQk',
    appId: '1:1085502128077:android:f1faa8ac6bfbb99cd60e84',
    messagingSenderId: '1085502128077',
    projectId: 'quiz-app-7e9b3',
    storageBucket: 'quiz-app-7e9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUvsBC2qAbvaYIg77dzzAgfYlx-UgYMeo',
    appId: '1:1085502128077:ios:94e4e3a448191bdad60e84',
    messagingSenderId: '1085502128077',
    projectId: 'quiz-app-7e9b3',
    storageBucket: 'quiz-app-7e9b3.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUvsBC2qAbvaYIg77dzzAgfYlx-UgYMeo',
    appId: '1:1085502128077:ios:94e4e3a448191bdad60e84',
    messagingSenderId: '1085502128077',
    projectId: 'quiz-app-7e9b3',
    storageBucket: 'quiz-app-7e9b3.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXbW3WGWdEJL8iIzWHVHlwUzdYmOuTpLA',
    appId: '1:1085502128077:web:7a8538ad855cfeabd60e84',
    messagingSenderId: '1085502128077',
    projectId: 'quiz-app-7e9b3',
    authDomain: 'quiz-app-7e9b3.firebaseapp.com',
    storageBucket: 'quiz-app-7e9b3.appspot.com',
    measurementId: 'G-CPPKJ45P4W',
  );
}
